### ISSUE TITLE
Some possible improvements.

### ISSUE THREAD

**Issue by YellowOnion** [BirkhoffLee/trash_doves_extract#1]
I made some quick and dirty changes: https://gist.github.com/YellowOnion/03b78251e1f86a1efca8362d262be452

uses command line arguments, the layout is more straightforward, you specify the height (minus the last row) and the width, and you specify the length of the last row.

Outputs is padded with zeros for early frames to work better with 3rd party apps (like ffmpeg or imagemagick)

**Comment by birkhofflee** [comment]
Great! I will merge if you’re willing to submit a PR
